package com.selflearningcoursecreationapp.utils

object ApiEndPoints {
    const val BASE_URL_INTERNAL = "https://selflearndevweb.appskeeper.in/info/"
    const val LINK_TERM_COND = "terms-&-conditions"
    const val LINK_PRIVECY_POL = "privacy-policy"
    const val LINK_ABOUT_US = "about-us"
    const val LINK_FAQ = "faq"

    const val BASE_URL = "https://appinventivlearningclientapi20220314151937.azurewebsites.net/Api/"
    const val API_SIGNUP = "SignUp/SignUpRequest"
    const val API_OTP_REQ = "SignUp/OtpRequest"
    const val API_OTP_VAL = "SignUp/ValidateOtpRequest"
    const val API_LOGIN = "Login"
    const val API_GET_CATEGORIES = "Category/GetCategoryList"
    const val API_MYCATEGORIES = "Category/MyCategories"
    const val API_SAVE_PREFRENCE = "Preferences/SavePreferences"
    const val API_GETTHEME_LIST = "Themes/GetThemesList"
    const val API_VIEW_PROFILE = "User/ViewProfile"
    const val API_CHANGE_PASS = "User/ChangePasswordRequest"
    const val API_RESET_PASS = "User/ResetPassword"
    const val API_UPDATE_PROFILE = "User/UpdateProfile"
    const val API_DELETE_ACCOUNT = "User/Delete"
    const val API_LOGOUT = "User/Logout"
    const val API_PROFESSION = "Profession/GetProfessionsList"
    const val API_GET_ALL_STATES = "Master/GetAllStates"
    const val API_GET_ALL_CITY = "Master/GetCitiesByStateId"
    const val API_ADD_PASSWORD = "User/AddPassword"
    const val API_ADD_EMAIL = "SignUp/OtpRequestForEmailChange"
    const val API_VERIFY_EMAIL = "SignUp/ValidateOtpRequestForEmailChange"
}